<?php

use yii\db\Schema;
use yii\db\Migration;

class m160201_134815_country_insert extends Migration
{
    public function up() {
        $sql = "INSERT INTO `country` VALUES (null, 'AF', 'Afghanistan',0);
INSERT INTO `country` VALUES (null, 'AL', 'Albania',0);
INSERT INTO `country` VALUES (null, 'DZ', 'Algeria',0);
INSERT INTO `country` VALUES (null, 'DS', 'American Samoa',0);
INSERT INTO `country` VALUES (null, 'AD', 'Andorra',0);
INSERT INTO `country` VALUES (null, 'AO', 'Angola',0);
INSERT INTO `country` VALUES (null, 'AI', 'Anguilla',0);
INSERT INTO `country` VALUES (null, 'AQ', 'Antarctica',0);
INSERT INTO `country` VALUES (null, 'AG', 'Antigua and Barbuda',0);
INSERT INTO `country` VALUES (null, 'AR', 'Argentina',0);
INSERT INTO `country` VALUES (null, 'AM', 'Armenia',0);
INSERT INTO `country` VALUES (null, 'AW', 'Aruba',0);
INSERT INTO `country` VALUES (null, 'AU', 'Australia',0);
INSERT INTO `country` VALUES (null, 'AT', 'Austria',0);
INSERT INTO `country` VALUES (null, 'AZ', 'Azerbaijan',0);
INSERT INTO `country` VALUES (null, 'BS', 'Bahamas',0);
INSERT INTO `country` VALUES (null, 'BH', 'Bahrain',0);
INSERT INTO `country` VALUES (null, 'BD', 'Bangladesh',0);
INSERT INTO `country` VALUES (null, 'BB', 'Barbados',0);
INSERT INTO `country` VALUES (null, 'BY', 'Belarus',0);
INSERT INTO `country` VALUES (null, 'BE', 'Belgium',0);
INSERT INTO `country` VALUES (null, 'BZ', 'Belize',0);
INSERT INTO `country` VALUES (null, 'BJ', 'Benin',0);
INSERT INTO `country` VALUES (null, 'BM', 'Bermuda',0);
INSERT INTO `country` VALUES (null, 'BT', 'Bhutan',0);
INSERT INTO `country` VALUES (null, 'BO', 'Bolivia',0);
INSERT INTO `country` VALUES (null, 'BA', 'Bosnia and Herzegovina',0);
INSERT INTO `country` VALUES (null, 'BW', 'Botswana',0);
INSERT INTO `country` VALUES (null, 'BV', 'Bouvet Island',0);
INSERT INTO `country` VALUES (null, 'BR', 'Brazil',0);
INSERT INTO `country` VALUES (null, 'IO', 'British Indian Ocean Territory',0);
INSERT INTO `country` VALUES (null, 'BN', 'Brunei Darussalam',0);
INSERT INTO `country` VALUES (null, 'BG', 'Bulgaria',0);
INSERT INTO `country` VALUES (null, 'BF', 'Burkina Faso',0);
INSERT INTO `country` VALUES (null, 'BI', 'Burundi',0);
INSERT INTO `country` VALUES (null, 'KH', 'Cambodia',0);
INSERT INTO `country` VALUES (null, 'CM', 'Cameroon',0);
INSERT INTO `country` VALUES (null, 'CA', 'Canada',0);
INSERT INTO `country` VALUES (null, 'CV', 'Cape Verde',0);
INSERT INTO `country` VALUES (null, 'KY', 'Cayman Islands',0);
INSERT INTO `country` VALUES (null, 'CF', 'Central African Republic',0);
INSERT INTO `country` VALUES (null, 'TD', 'Chad',0);
INSERT INTO `country` VALUES (null, 'CL', 'Chile',0);
INSERT INTO `country` VALUES (null, 'CN', 'China',0);
INSERT INTO `country` VALUES (null, 'CX', 'Christmas Island',0);
INSERT INTO `country` VALUES (null, 'CC', 'Cocos (Keeling) Islands',0);
INSERT INTO `country` VALUES (null, 'CO', 'Colombia',0);
INSERT INTO `country` VALUES (null, 'KM', 'Comoros',0);
INSERT INTO `country` VALUES (null, 'CG', 'Congo',0);
INSERT INTO `country` VALUES (null, 'CK', 'Cook Islands',0);
INSERT INTO `country` VALUES (null, 'CR', 'Costa Rica',0);
INSERT INTO `country` VALUES (null, 'HR', 'Croatia (Hrvatska)',0);
INSERT INTO `country` VALUES (null, 'CU', 'Cuba',0);
INSERT INTO `country` VALUES (null, 'CY', 'Cyprus',0);
INSERT INTO `country` VALUES (null, 'CZ', 'Czech Republic',0);
INSERT INTO `country` VALUES (null, 'DK', 'Denmark',0);
INSERT INTO `country` VALUES (null, 'DJ', 'Djibouti',0);
INSERT INTO `country` VALUES (null, 'DM', 'Dominica',0);
INSERT INTO `country` VALUES (null, 'DO', 'Dominican Republic',0);
INSERT INTO `country` VALUES (null, 'TP', 'East Timor',0);
INSERT INTO `country` VALUES (null, 'EC', 'Ecuador',0);
INSERT INTO `country` VALUES (null, 'EG', 'Egypt',0);
INSERT INTO `country` VALUES (null, 'SV', 'El Salvador',0);
INSERT INTO `country` VALUES (null, 'GQ', 'Equatorial Guinea',0);
INSERT INTO `country` VALUES (null, 'ER', 'Eritrea',0);
INSERT INTO `country` VALUES (null, 'EE', 'Estonia',0);
INSERT INTO `country` VALUES (null, 'ET', 'Ethiopia',0);
INSERT INTO `country` VALUES (null, 'FK', 'Falkland Islands (Malvinas)',0);
INSERT INTO `country` VALUES (null, 'FO', 'Faroe Islands',0);
INSERT INTO `country` VALUES (null, 'FJ', 'Fiji',0);
INSERT INTO `country` VALUES (null, 'FI', 'Finland',0);
INSERT INTO `country` VALUES (null, 'FR', 'France',0);
INSERT INTO `country` VALUES (null, 'FX', 'France, Metropolitan',0);
INSERT INTO `country` VALUES (null, 'GF', 'French Guiana',0);
INSERT INTO `country` VALUES (null, 'PF', 'French Polynesia',0);
INSERT INTO `country` VALUES (null, 'TF', 'French Southern Territories',0);
INSERT INTO `country` VALUES (null, 'GA', 'Gabon',0);
INSERT INTO `country` VALUES (null, 'GM', 'Gambia',0);
INSERT INTO `country` VALUES (null, 'GE', 'Georgia',0);
INSERT INTO `country` VALUES (null, 'DE', 'Germany',0);
INSERT INTO `country` VALUES (null, 'GH', 'Ghana',0);
INSERT INTO `country` VALUES (null, 'GI', 'Gibraltar',0);
INSERT INTO `country` VALUES (null, 'GK', 'Guernsey',0);
INSERT INTO `country` VALUES (null, 'GR', 'Greece',0);
INSERT INTO `country` VALUES (null, 'GL', 'Greenland',0);
INSERT INTO `country` VALUES (null, 'GD', 'Grenada',0);
INSERT INTO `country` VALUES (null, 'GP', 'Guadeloupe',0);
INSERT INTO `country` VALUES (null, 'GU', 'Guam',0);
INSERT INTO `country` VALUES (null, 'GT', 'Guatemala',0);
INSERT INTO `country` VALUES (null, 'GN', 'Guinea',0);
INSERT INTO `country` VALUES (null, 'GW', 'Guinea-Bissau',0);
INSERT INTO `country` VALUES (null, 'GY', 'Guyana',0);
INSERT INTO `country` VALUES (null, 'HT', 'Haiti',0);
INSERT INTO `country` VALUES (null, 'HM', 'Heard and Mc Donald Islands',0);
INSERT INTO `country` VALUES (null, 'HN', 'Honduras',0);
INSERT INTO `country` VALUES (null, 'HK', 'Hong Kong',0);
INSERT INTO `country` VALUES (null, 'HU', 'Hungary',0);
INSERT INTO `country` VALUES (null, 'IS', 'Iceland',0);
INSERT INTO `country` VALUES (null, 'IN', 'India',0);
INSERT INTO `country` VALUES (null, 'IM', 'Isle of Man',0);
INSERT INTO `country` VALUES (null, 'ID', 'Indonesia',0);
INSERT INTO `country` VALUES (null, 'IR', 'Iran (Islamic Republic of)',0);
INSERT INTO `country` VALUES (null, 'IQ', 'Iraq',0);
INSERT INTO `country` VALUES (null, 'IE', 'Ireland',0);
INSERT INTO `country` VALUES (null, 'IL', 'Israel',0);
INSERT INTO `country` VALUES (null, 'IT', 'Italy',0);
INSERT INTO `country` VALUES (null, 'CI', 'Ivory Coast',0);
INSERT INTO `country` VALUES (null, 'JE', 'Jersey',0);
INSERT INTO `country` VALUES (null, 'JM', 'Jamaica',0);
INSERT INTO `country` VALUES (null, 'JP', 'Japan',0);
INSERT INTO `country` VALUES (null, 'JO', 'Jordan',0);
INSERT INTO `country` VALUES (null, 'KZ', 'Kazakhstan',0);
INSERT INTO `country` VALUES (null, 'KE', 'Kenya',0);
INSERT INTO `country` VALUES (null, 'KI', 'Kiribati',0);
INSERT INTO `country` VALUES (null, 'KP', 'Korea, Democratic People''s Republic of',0);
INSERT INTO `country` VALUES (null, 'KR', 'Korea, Republic of',0);
INSERT INTO `country` VALUES (null, 'XK', 'Kosovo',0);
INSERT INTO `country` VALUES (null, 'KW', 'Kuwait',0);
INSERT INTO `country` VALUES (null, 'KG', 'Kyrgyzstan',0);
INSERT INTO `country` VALUES (null, 'LA', 'Lao People''s Democratic Republic',0);
INSERT INTO `country` VALUES (null, 'LV', 'Latvia',0);
INSERT INTO `country` VALUES (null, 'LB', 'Lebanon',0);
INSERT INTO `country` VALUES (null, 'LS', 'Lesotho',0);
INSERT INTO `country` VALUES (null, 'LR', 'Liberia',0);
INSERT INTO `country` VALUES (null, 'LY', 'Libyan Arab Jamahiriya',0);
INSERT INTO `country` VALUES (null, 'LI', 'Liechtenstein',0);
INSERT INTO `country` VALUES (null, 'LT', 'Lithuania',0);
INSERT INTO `country` VALUES (null, 'LU', 'Luxembourg',0);
INSERT INTO `country` VALUES (null, 'MO', 'Macau',0);
INSERT INTO `country` VALUES (null, 'MK', 'Macedonia',0);
INSERT INTO `country` VALUES (null, 'MG', 'Madagascar',0);
INSERT INTO `country` VALUES (null, 'MW', 'Malawi',0);
INSERT INTO `country` VALUES (null, 'MY', 'Malaysia',0);
INSERT INTO `country` VALUES (null, 'MV', 'Maldives',0);
INSERT INTO `country` VALUES (null, 'ML', 'Mali',0);
INSERT INTO `country` VALUES (null, 'MT', 'Malta',0);
INSERT INTO `country` VALUES (null, 'MH', 'Marshall Islands',0);
INSERT INTO `country` VALUES (null, 'MQ', 'Martinique',0);
INSERT INTO `country` VALUES (null, 'MR', 'Mauritania',0);
INSERT INTO `country` VALUES (null, 'MU', 'Mauritius',0);
INSERT INTO `country` VALUES (null, 'TY', 'Mayotte',0);
INSERT INTO `country` VALUES (null, 'MX', 'Mexico',0);
INSERT INTO `country` VALUES (null, 'FM', 'Micronesia, Federated States of',0);
INSERT INTO `country` VALUES (null, 'MD', 'Moldova, Republic of',0);
INSERT INTO `country` VALUES (null, 'MC', 'Monaco',0);
INSERT INTO `country` VALUES (null, 'MN', 'Mongolia',0);
INSERT INTO `country` VALUES (null, 'ME', 'Montenegro',0);
INSERT INTO `country` VALUES (null, 'MS', 'Montserrat',0);
INSERT INTO `country` VALUES (null, 'MA', 'Morocco',0);
INSERT INTO `country` VALUES (null, 'MZ', 'Mozambique',0);
INSERT INTO `country` VALUES (null, 'MM', 'Myanmar',0);
INSERT INTO `country` VALUES (null, 'NA', 'Namibia',0);
INSERT INTO `country` VALUES (null, 'NR', 'Nauru',0);
INSERT INTO `country` VALUES (null, 'NP', 'Nepal',0);
INSERT INTO `country` VALUES (null, 'NL', 'Netherlands',0);
INSERT INTO `country` VALUES (null, 'AN', 'Netherlands Antilles',0);
INSERT INTO `country` VALUES (null, 'NC', 'New Caledonia',0);
INSERT INTO `country` VALUES (null, 'NZ', 'New Zealand',0);
INSERT INTO `country` VALUES (null, 'NI', 'Nicaragua',0);
INSERT INTO `country` VALUES (null, 'NE', 'Niger',0);
INSERT INTO `country` VALUES (null, 'NG', 'Nigeria',0);
INSERT INTO `country` VALUES (null, 'NU', 'Niue',0);
INSERT INTO `country` VALUES (null, 'NF', 'Norfolk Island',0);
INSERT INTO `country` VALUES (null, 'MP', 'Northern Mariana Islands',0);
INSERT INTO `country` VALUES (null, 'NO', 'Norway',0);
INSERT INTO `country` VALUES (null, 'OM', 'Oman',0);
INSERT INTO `country` VALUES (null, 'PK', 'Pakistan',0);
INSERT INTO `country` VALUES (null, 'PW', 'Palau',0);
INSERT INTO `country` VALUES (null, 'PS', 'Palestine',0);
INSERT INTO `country` VALUES (null, 'PA', 'Panama',0);
INSERT INTO `country` VALUES (null, 'PG', 'Papua New Guinea',0);
INSERT INTO `country` VALUES (null, 'PY', 'Paraguay',0);
INSERT INTO `country` VALUES (null, 'PE', 'Peru',0);
INSERT INTO `country` VALUES (null, 'PH', 'Philippines',0);
INSERT INTO `country` VALUES (null, 'PN', 'Pitcairn',0);
INSERT INTO `country` VALUES (null, 'PL', 'Poland',0);
INSERT INTO `country` VALUES (null, 'PT', 'Portugal',0);
INSERT INTO `country` VALUES (null, 'PR', 'Puerto Rico',0);
INSERT INTO `country` VALUES (null, 'QA', 'Qatar',0);
INSERT INTO `country` VALUES (null, 'RE', 'Reunion',0);
INSERT INTO `country` VALUES (null, 'RO', 'Romania',0);
INSERT INTO `country` VALUES (null, 'RU', 'Russian Federation',0);
INSERT INTO `country` VALUES (null, 'RW', 'Rwanda',0);
INSERT INTO `country` VALUES (null, 'KN', 'Saint Kitts and Nevis',0);
INSERT INTO `country` VALUES (null, 'LC', 'Saint Lucia',0);
INSERT INTO `country` VALUES (null, 'VC', 'Saint Vincent and the Grenadines',0);
INSERT INTO `country` VALUES (null, 'WS', 'Samoa',0);
INSERT INTO `country` VALUES (null, 'SM', 'San Marino',0);
INSERT INTO `country` VALUES (null, 'ST', 'Sao Tome and Principe',0);
INSERT INTO `country` VALUES (null, 'SA', 'Saudi Arabia',0);
INSERT INTO `country` VALUES (null, 'SN', 'Senegal',0);
INSERT INTO `country` VALUES (null, 'RS', 'Serbia',0);
INSERT INTO `country` VALUES (null, 'SC', 'Seychelles',0);
INSERT INTO `country` VALUES (null, 'SL', 'Sierra Leone',0);
INSERT INTO `country` VALUES (null, 'SG', 'Singapore',0);
INSERT INTO `country` VALUES (null, 'SK', 'Slovakia',0);
INSERT INTO `country` VALUES (null, 'SI', 'Slovenia',0);
INSERT INTO `country` VALUES (null, 'SB', 'Solomon Islands',0);
INSERT INTO `country` VALUES (null, 'SO', 'Somalia',0);
INSERT INTO `country` VALUES (null, 'ZA', 'South Africa',0);
INSERT INTO `country` VALUES (null, 'GS', 'South Georgia South Sandwich Islands',0);
INSERT INTO `country` VALUES (null, 'ES', 'Spain',0);
INSERT INTO `country` VALUES (null, 'LK', 'Sri Lanka',0);
INSERT INTO `country` VALUES (null, 'SH', 'St. Helena',0);
INSERT INTO `country` VALUES (null, 'PM', 'St. Pierre and Miquelon',0);
INSERT INTO `country` VALUES (null, 'SD', 'Sudan',0);
INSERT INTO `country` VALUES (null, 'SR', 'Suriname',0);
INSERT INTO `country` VALUES (null, 'SJ', 'Svalbard and Jan Mayen Islands',0);
INSERT INTO `country` VALUES (null, 'SZ', 'Swaziland',0);
INSERT INTO `country` VALUES (null, 'SE', 'Sweden',0);
INSERT INTO `country` VALUES (null, 'CH', 'Switzerland',0);
INSERT INTO `country` VALUES (null, 'SY', 'Syrian Arab Republic',0);
INSERT INTO `country` VALUES (null, 'TW', 'Taiwan',0);
INSERT INTO `country` VALUES (null, 'TJ', 'Tajikistan',0);
INSERT INTO `country` VALUES (null, 'TZ', 'Tanzania, United Republic of',0);
INSERT INTO `country` VALUES (null, 'TH', 'Thailand',0);
INSERT INTO `country` VALUES (null, 'TG', 'Togo',0);
INSERT INTO `country` VALUES (null, 'TK', 'Tokelau',0);
INSERT INTO `country` VALUES (null, 'TO', 'Tonga',0);
INSERT INTO `country` VALUES (null, 'TT', 'Trinidad and Tobago',0);
INSERT INTO `country` VALUES (null, 'TN', 'Tunisia',0);
INSERT INTO `country` VALUES (null, 'TR', 'Turkey',0);
INSERT INTO `country` VALUES (null, 'TM', 'Turkmenistan',0);
INSERT INTO `country` VALUES (null, 'TC', 'Turks and Caicos Islands',0);
INSERT INTO `country` VALUES (null, 'TV', 'Tuvalu',0);
INSERT INTO `country` VALUES (null, 'UG', 'Uganda',0);
INSERT INTO `country` VALUES (null, 'UA', 'Ukraine',0);
INSERT INTO `country` VALUES (null, 'AE', 'United Arab Emirates',0);
INSERT INTO `country` VALUES (null, 'GB', 'United Kingdom',0);
INSERT INTO `country` VALUES (null, 'US', 'United States',0);
INSERT INTO `country` VALUES (null, 'UM', 'United States minor outlying islands',0);
INSERT INTO `country` VALUES (null, 'UY', 'Uruguay',0);
INSERT INTO `country` VALUES (null, 'UZ', 'Uzbekistan',0);
INSERT INTO `country` VALUES (null, 'VU', 'Vanuatu',0);
INSERT INTO `country` VALUES (null, 'VA', 'Vatican City State',0);
INSERT INTO `country` VALUES (null, 'VE', 'Venezuela',0);
INSERT INTO `country` VALUES (null, 'VN', 'Vietnam',0);
INSERT INTO `country` VALUES (null, 'VG', 'Virgin Islands (British)',0);
INSERT INTO `country` VALUES (null, 'VI', 'Virgin Islands (U.S.)',0);
INSERT INTO `country` VALUES (null, 'WF', 'Wallis and Futuna Islands',0);
INSERT INTO `country` VALUES (null, 'EH', 'Western Sahara',0);
INSERT INTO `country` VALUES (null, 'YE', 'Yemen',0);
INSERT INTO `country` VALUES (null, 'YU', 'Yugoslavia',0);
INSERT INTO `country` VALUES (null, 'ZR', 'Zaire',0);
INSERT INTO `country` VALUES (null, 'ZM', 'Zambia',0);
INSERT INTO `country` VALUES (null, 'ZW', 'Zimbabwe',0);";

        $this->execute($sql);
    }

    public function down() {
        $this->truncateTable("country");
    }

    /*
    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
    }

    public function safeDown()
    {
    }
    */
}
